# Copyright (c) 2025 TiaC Systems
# SPDX-License-Identifier: Unlicense

name: Sync CANnectivity Forks

on:
  schedule: # At minute 0 past every 4th hour.
    - cron: '0 */4 * * *'
  workflow_dispatch: # And manually on button click.

jobs:
  git-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - cannectivity
        branch:
          - main
          - v1.3-branch
          - v1.2-branch
          - v1.1-branch
          - v1.0-branch
          - "refs/tags/*"

    steps:
      - name: git-sync-cannectivity
        uses: tiacsys/git-sync@v3
        with:
          source_repo: "git@github.com:CANnectivity/${{ matrix.repo }}.git"
          source_branch: "${{ matrix.branch }}"
          destination_repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ZEPHYR }}
        if: ${{ matrix.repo == 'cannectivity' }}

  git-rebase:
    runs-on: ubuntu-latest

    needs: git-sync

    strategy:
      matrix:
        repo:
          - cannectivity
        branch:
          - main
          - v1.3-branch
          - v1.2-branch
          - v1.1-branch
          - v1.0-branch

    steps:
      - name: git-rebase-cannectivity
        uses: tiacsys/git-rebase@v1
        with:
          repo: "git@github.com:tiacsys/${{ matrix.repo }}.git"
          source_branch: "tiacsys/${{ matrix.branch }}"
          destination_branch: "${{ matrix.branch }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_ZEPHYR }}
        if: ${{ matrix.repo == 'cannectivity' }}
